sudo: true
language: ruby
cache:
  directories:
  - unicorn
rvm:
- 2.4.1
install:
- if [[ ! -d unicorn/.git ]]; then git clone https://github.com/misson20000/unicorn.git
  -b all_features; fi
- gem install bundler -v 1.16.1
- cd unicorn; git fetch origin all_features; git reset --hard origin/all_features;
  ./make.sh && sudo ./make.sh install && cd bindings/ruby/unicorn_gem && rake install
  && cd ../../../../
- bundle install
script: rspec
env:
  global:
  - secure: W4SKs2A7nPa6Y+N+m+rh2pu6uaIswzElnJZYN6nVEyctQycYim4V8hde1KANrwJj7m1QcXZMHUObGkNwp26uyKwP4VBLeoBB0ArH2hCsxG4iDqWvOEUFJvNnJE5QJguqUNWf/DR4B0XY6c4eqGVS+gG3yhG1Ao8/J5/TNJOkVPe/+pQxaQ80WnfYPo04KmwcY4vPi636EArTBhgHGMSHmUxTbOLzN16cDyxadV3w3PlDm67ny5OGAMxEu0eRR2lTVCz6KcWsjZU+LIFUWQoMcB4U2u1MG9Mq3M4tHGlIseV/wG9Yn2UBPmko2QlOEE5sQ16++UbUWibvV88Y6ccKdoPL0YaiSm9tBl3x78Zmrg9oxutcVcoJj/nfsMuEFms3eEfPx0aZDc4Cc+2P6vt8bJBGbaBzAVsw0lTnKl8CiXGXyvNf+oInLB1JPEXzgS4UK9bekRVpvg8PlDVbh/eHtQm/UKZ9mSVzP28Pni8XwhdI2dHIU4l0WDdnACso9WTchNtloxjaCNGnJRpJ62v9+9tQST0bvjV9twSdFR45R65o52lpAuS3q47Rd4OXgBPjoyNMYfR0i6HOUuNPzgve8cRj9W/qboDfZ8p5LxWEtUuLISQe4T19JZQYG/9BlwCWSR6+869kx/J51SmLbhTf0gEog0kL3JTrZVo2r+VN7Z8=
  - secure: WcvzYMPxoj93jwYp/wwNDc6GKmbgJPRqrwNuMRL1jckN+tg5HshAgX52c5qaAJeudgFKxnUnReepBfWZI38TdbAn/YO72G5jakIC+xKfDM9bMy5sSUfG2Irg45f/AXYoD0USDZ2pNc/rpkE1An71LaJnSwt6C2rARn87a2/rBxr523HSQKqp5wr1F7q7ZseIxmvcrOwPnDOT1JjsqfBffXnXgSPOK1reA08wnOGkupoDgJWrXqrUNVQ10yLYcoLUCV/24quptJ0fX1IGQS123HxzV0bhkj5v7w/SB490E/bJRq29oXzhcDHYAvtwGC511fB/wWDtov4hadLHEZLE6f38wOdbLE+vJ/7CnLnsWxOBJHojPOpCUR6GqWI3c8+wchAwvzvvnK/tyQDRZ4rKRoAIehmpSTfVWMssHvwvokUpJbZ3tSfmLcg4dDeMgWC1G0K+YFgiUdEudtutrj1zV1s6Kgaa6mR8/cBxuALp8X5tQKI+Na2lF8651yL6opeLdASuAwkZ6D87GkpkB9vRfkh/4jgkWYFt1e841+k3WNg5XBRTvVkslliJtLyOLXRGYu9gbdxCmrTdP1huiX9Tf2PtQ74CUnG3gCq/j96YOZ3aKzHZ3KgjdRh+epUdm1g8T0XI4zlu4oJgdJaPWi5kyOKNUy7KaVDfU8ZDGz6IRV0=
  matrix:
    - RTLD: A571927D65DC2BECA04492F25AE2F9D30CDBA6EB000000000000000000000000
#    - RTLD: BFA53AB299BDB0F3FDA4A691C991C33D1E05FCD9000000000000000000000000
